language: node_js
notifications:
  email: false
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script: npm ls >/dev/null
deploy:
  provider: script
  skip_cleanup: true
  script: DEBUG=dont-crack npx semantic-release
